import Head from "next/head";
import Styles from "../styles/pages/Users.module.scss";
import { Input, Button, Modal, Avatar, Row, Col } from "antd";
import { BsSearch } from "react-icons/bs";
import UserList from "../components/UserList";
import { useState, useEffect, useRef } from "react";
import useGroups from "../hooks/groups";

export default function Users() {
  const { groups, isLoading } = useGroups();

  if (isLoading) {
    return <div>Loading...</div>;
  }
  return (
    <div className={Styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.header}>
        <div className={Styles.pageHeading}>Groups</div>
      </div>

      {Array.from(groups, ([key, value]) => {
        return <UserList key={key} header={key} users={value} group={true} />;
      })}
    </div>
  );
}
