import Head from "next/head";
import Image from "next/image";
import styles from "../styles/pages/Home.module.scss";
import Sidebar from "../components/Sidebar";

export default function Groups() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Groups
    </div>
  );
}
