import Head from "next/head";
import Styles from "../styles/pages/Users.module.scss";
import { Input, Button } from "antd";
import { BsSearch } from "react-icons/bs";
import UserList from "../components/UserList";

export default function Users() {
  return (
    <div className={Styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.header}>
        <div className={Styles.pageHeading}>Users</div>
        <Input size="large" placeholder="Search" prefix={<BsSearch />} />
        <Button size="large">Search</Button>
      </div>
      <UserList />
    </div>
  );
}
